# Generated by Django 4.1.7 on 2023-07-19 18:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_pokemon'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pokemon',
            name='evolves_from',
        ),
        migrations.RemoveField(
            model_name='pokemon',
            name='evolves_to',
        ),
    ]
